spring.application.name=media-processor
spring.rabbitmq.host=${RMQ_HOST}
spring.rabbitmq.username=${RMQ_USERNAME}
spring.rabbitmq.password=${RMQ_PASSWORD}
spring.rabbitmq.virtual-host=${RMQ_VIRTUAL_HOST}